@extends('layouts.app')

@section('content')
<div class="utility-page-wrap"><div class="utility-page-content w-password-page w-form"><form action="/.wf_auth" class="utility-page-form password-protected w-password-page" data-name="Email Form" data-wf-element-id="67d683d0ddabe333623d49fe00000000000c" data-wf-page-id="67d683d0ddabe333623d49fb" id="email-form" method="post" name="email-form"><img alt="" class="password-protected-image" src="{{ asset('assets/cdn_prod_website-files_com/67c0042b87279d5a0f828374/67d79536612e79f3705f2e04_Lock_20Image.png') }}"/><h1 class="protected-title">Password Protected</h1><p class="protected-text">A password-protected page is a webpage on a website requires users to enter a new specific password.</p><label class="hidden w-password-page" for="pass">Password</label><div class="password-protected-fields-wrapper"><input autofocus="true" class="form-field w-password-page w-input" data-name="field" id="pass" maxlength="256" name="pass" placeholder="Enter Password" type="password"/><input class="form-button w-password-page w-button" data-wait="Please wait..." type="submit" value="Submit Now"/></div><div class="w-password-page w-form-fail"><div>Incorrect password. Please try again.</div></div><div class="w-password-page w-embed w-script" style="display:none"><input name="path" type="hidden" value="&lt;%WF_FORM_VALUE_PATH%&gt;"/><input name="page" type="hidden" value="&lt;%WF_FORM_VALUE_PAGE%&gt;"/></div><div class="w-password-page w-embed w-script" style="display:none"><script type="application/javascript">(function _handlePasswordPageOnload() {
	  if (/[?&]e=1(&|$)/.test(document.location.search)) {
	    document.querySelector('.w-password-page.w-form-fail').style.display = 'block';
	  }
	})()</script></div></form></div></div><script crossorigin="anonymous" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" src="{{ asset('assets/d3e54v103j8qbb_cloudfront_net/js/jquery-3.5.1.min.dc5e7f18c8.js') }}" type="text/javascript"></script><script src="{{ asset('assets/cdn_prod_website-files_com/67c0042b87279d5a0f828374/js/webflow.schunk.4a394eb5af8156f2.js') }}" type="text/javascript"></script><script src="{{ asset('assets/cdn_prod_website-files_com/67c0042b87279d5a0f828374/js/webflow.schunk.049b9a75544a0bc5.js') }}" type="text/javascript"></script><script src="{{ asset('assets/cdn_prod_website-files_com/67c0042b87279d5a0f828374/js/webflow.schunk.ef7080c06606ca1c.js') }}" type="text/javascript"></script><script src="{{ asset('assets/cdn_prod_website-files_com/67c0042b87279d5a0f828374/js/webflow.2a831961.cd7595da1e067cec.js') }}" type="text/javascript"></script>
@endsection
